version: '3.7'
services:
  web:
    build: 
      context: web/
      dockerfile: Dockerfile
    depends_on: 
      db:
        condition: service_healthy
    networks:
    - mynetwork
    ports:
    - 80:80
  db:
    build: 
      context: db/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: db/database/db-files
        target: /var/lib/mysql
    # volumes:
    # - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: cee_db
    networks:
    - mynetwork
    # ports:
    # - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
networks:
  mynetwork:
    name: mynetwork
# volumes:
#   db_data: {}